name: AnyGym
options:
  bundleIdPrefix: com.anygym
  deploymentTarget:
    iOS: "15.0"
  developmentLanguage: en
  xcodeVersion: "14.0"

packages:
  Auth0:
    url: https://github.com/auth0/Auth0.swift
    from: 2.0.0

targets:
  AnyGym:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: .
        excludes:
          - "*.md"
          - ".gitignore"
          - "project.yml"
    info:
      path: Info.plist
      properties:
        CFBundleDisplayName: AnyGym
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        UILaunchScreen:
          UIColorName: LaunchScreenBackground
          UIImageName: LaunchScreen
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: true
        CFBundleURLTypes:
          - CFBundleTypeRole: Editor
            CFBundleURLName: com.anygym.app
            CFBundleURLSchemes:
              - $(PRODUCT_BUNDLE_IDENTIFIER)
    dependencies:
      - package: Auth0
        product: Auth0
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.anygym.app
        SWIFT_VERSION: "5.9"
        TARGETED_DEVICE_FAMILY: "1,2"
        IPHONEOS_DEPLOYMENT_TARGET: "15.0"
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic

